
#httpclient配置参数
#http:
#  #最大连接数
#  maxTotal: 100
#  #并发数
#  defaultMaxPerRoute: 20
#  #创建连接的最长时间
#  connectTimeout: 1000
#  #从连接池中获取到连接的最长时间
#  connectionRequestTimeout: 500
#  #数据传输的最长时间
#  socketTimeout: 10000
#  #提交请求前测试连接是否可用
#  staleConnectionCheckEnabled: true

#mybatis-plus配置参数
mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
 # global-config:
 #   db-config:
 #     id-type: auto
 #     field-strategy: not_null
 #     #驼峰下划线转换
 #     column-underline: true
 #     db-type: mysql
 #     logic-delete-value: 1
 #     logic-not-delete-value: 0
 # configuration:
 #   map-underscore-to-camel-case: true
 #   cache-enabled: false

server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    #hikari:
    #  maximum-pool-size: 13